### ISSUE TITLE
How to get error message when onError

### ISSUE THREAD

**Issue by fjr619** [skydoves/Sandwich#18]
```
    data class Error<T>(val response: Response<T>) : ApiResponse<T>() {
      val statusCode: StatusCode = getStatusCodeFromResponse(response)
      val headers: Headers = response.headers()
      val raw: okhttp3.Response = response.raw()
      val errorBody: ResponseBody? = response.errorBody()
      override fun toString(): String = "[ApiResponse.Failure.Error-$statusCode](errorResponse=$response)"
    }
```
how to get error message? because when i used `apiResponse.message()` it will return like in `toString()` function. what i want just message only. thank you

**Comment by skydoves** [comment]
Hi, you can access the `Response` on the `ApiResponse.Failure.Error`, and you can get a `ResponseBody` using the below codes.

```kotlin
response.errorBody()
```

Thanks :)

**Comment by Faizanbasri-smartis** [comment]
how to get message from errorBody

**Comment by skydoves** [comment]
You can get the pure string message with the following code: `response.message()`

**Comment by Faizanbasri-smartis** [comment]
I need to get message in json, that is customize message. how can i use errorbody with customize error class

**Comment by Al-Hussein-96** [comment]
@Faizanbasri-smartis  Is it solved ?

**Comment by Al-Hussein-96** [comment]
@Faizanbasri-smartis 
I get the answer:

use errorBody?.string() to get the body of error then you should parse it to your own object.
I try to parse the body in mapper but it was empty, I don't know why !!, so that I didn't use mapper.

    suspendOnError {

            runCatching {
                send(
                    Gson().fromJson(
                        errorBody?.string(),
                        SimpleResponse::class.java
                    )
                )
            }


        }
