### ISSUE TITLE
Interface can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type.

### ISSUE THREAD

**Issue by sahianmol1** [skydoves/sandwich#205]
- Library Version: 2.0.0
- Tested on Samsung galaxy S21 FE 5G and Pixel 7 Pro API 33 emulator

Add a clear description about the problem.
In my retrofit service interface I have a get API call

`@GET("/getSomeData/")
  suspend fun getData(): ApiResponse<List<<MyDataModel>>>
`
when I run the app after some time the app gets crashed with the below logs:

if I use Moshi Converter Factory - 
`java.lang.illegalArgumentException: Unable to create converter for com.skydoves.sandwich.ApiResponse<? extends java.util.List<com.packagename.MyDataModel>>`

if I use Gson Converter Factory -
`com.google.gson.JsonIOException: Interfaces can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Interface name: com.skydoves.sandwich.ApiResponse`

**Expected Behavior:**
The app should not crash.

**Comment by skydoves** [comment]
Hey @sahianmol1, which platform do you build? If it's Android platform, please follow the instructions below:

https://skydoves.github.io/sandwich/retrofit/

You can also find some use cases on the sample projects, such as [Pokedex](https://github.com/skydoves/pokedex).

**Comment by skydoves** [comment]
When you create your Retrofit adapter, please add the call adapter factory like the code below:

```kotlin
val retrofit = Retrofit.Builder()
    .baseUrl(BASE_URL)
    .addCallAdapterFactory(ApiResponseCallAdapterFactory.create())
    .build()
```
