### ISSUE TITLE
Difference Exception Handling between Ktor and Retrofit

### ISSUE THREAD

**Issue by chandroidx** [skydoves/sandwich#214]
For **Retrofit**, In **ApiResponseCallDelegate.kt**
The part that waits for the API response is within a try-catch block

```kotlin
  override fun enqueueImpl(callback: Callback<ApiResponse<T>>) {
    coroutineScope.launch {
      try {
        val response = proxy.awaitResponse()
        val apiResponse = ApiResponse.responseOf { response }
        callback.onResponse(this@ApiResponseCallDelegate, Response.success(apiResponse))
      } catch (e: Exception) {
        callback.onResponse(
          this@ApiResponseCallDelegate,
          Response.success(ApiResponse.exception(e)),
        )
      }
    }
  }
```
</br>

But for **Ktor**, In **HttpClientExtension.kt**
**'response'** already holds requested HttpResponse.
Therefore, within the try-catch block in **'apiResponseOf'**, it's not possible to handle errors occur during the request process
(e.g. UnknownHostException)
```kotlin
public suspend inline fun <reified T> HttpClient.getApiResponse(
  builder: HttpRequestBuilder,
): ApiResponse<T> {
  builder.method = HttpMethod.Get
  val response = request(builder)
  return apiResponseOf { response }
}
```

</br>
It seems more fitting for the purpose to pass the function itself as a parameter rather than receiving the result of the request

**Comment by skydoves** [comment]
This issue will be addressed in the upcoming stable release. Appreciate your report and contribution.
