### ISSUE TITLE
runAndRetry not working when type of ApiResponse had type variable

### ISSUE THREAD

**Issue by ldileh** [skydoves/sandwich#232]
hello @skydoves, i had a case like this. the endpoint return the json with template like @dempsey. my problem is when I created the base class for the response it's working. but when I'm trying to use runAndRetry extension, it's show the warning : 
`
Type mismatch.
Required:
Any
Found:
BaseResponse<TokenResponseModel>?
`

![Screenshot 2023-12-01 135918](https://github.com/skydoves/sandwich/assets/1288006/4dd074a9-d431-4603-af08-42411ab60fed)

but when i change the body without the BaseResponse model, the 'runAndRetry ' method working well without the warning show up. 

how do i solve this?

this is my base response model class 
`
@Keep
@Serializable
data class BaseResponse<T>(
    @SerializedName("error")
    val error: ErrorModel? = null,
    @SerializedName("success")
    val success: Boolean?,
    @SerializedName("data")
    val data: T? = null
)
`

_Originally posted by @ldileh in https://github.com/skydoves/sandwich/issues/30#issuecomment-1835573521_

**Comment by ldileh** [comment]
`otpVerification` return `ApiResponse<BaseResponse<TokenResponseModel>>`. 

inside the class BaseResponse is : 
`@Keep @Serializable data class BaseResponse<T>( @SerializedName("error") val error: ErrorModel? = null, @SerializedName("success") val success: Boolean?, @SerializedName("data") val data: T? = null )`

and for class TokenResponseModel is :
`@Keep
data class TokenResponseModel(
    @SerializedName("accessToken")
    val accessToken: String?,
    @SerializedName("refreshToken")
    val refreshToken: String?
)`

**Comment by skydoves** [comment]
@ldileh What happens if you add `!!` at the end of the `otpVerification` method?

**Comment by skydoves** [comment]
I just tested with the demo project and it looks work for me.

```kotlin
interface DisneyService {
  
  @GET("")
  suspend fun fetchItems(): ApiResponse<BaseResponse<List<Poster>>>
}

    val retryPolicy = object : RetryPolicy {
      override fun shouldRetry(attempt: Int, message: String?): Boolean = false

      override fun retryTimeout(attempt: Int, message: String?): Int  = 3
    }

    runAndRetry(retryPolicy) { _, _ ->
      disneyService.fetchItems()
    }
```

**Comment by ldileh** [comment]
oh great it's work! what happens in that part?

**Comment by ldileh** [comment]
then what if the body response had case null? how can I handle that part?

let's say, the problem is in the endpoint :
case 1:  success it returns json body
case 2 : It return success HTTP code, but for some reason, the body is null because the endpoint had a problem.

how can I handle case 2? it will turn to method `onError` or `onException` automatically?

**Comment by ldileh** [comment]
ah sorry @skydoves, I just read the documentation again. apparently I can use getOrNull(). stupid of me lol
thanks btw bro @skydoves for your support
