### ISSUE TITLE
deserializeErrorBody() throws internal exceptions

### ISSUE THREAD

**Issue by KovshefulCoder** [skydoves/sandwich#267]
**Please complete the following information:**
- Library Version 2.0.5
- Xiaomi 11T Pro
 
**Describe the Bug:**

deserializeErrorBody() extenstion throws all internal exceptions, for example in case of any decoding-specific error - SerializationException if @Serializable data class does not match with backend answer.

**Expected Behavior:**

deserializeErrorBody returns null if the error body is empty. Maybe add try catch on internal json.decodeFromString() to catch serialization exceptions and return null in case of this exception.
I can create pull request with such implementation

**Comment by KovshefulCoder** [comment]
Example:
![image](https://github.com/skydoves/sandwich/assets/84292117/8e405973-9897-49be-99cb-40f19ca704d7)
![image](https://github.com/skydoves/sandwich/assets/84292117/d26c5018-5f53-4b1e-998d-71cf55bc6b44)
![image](https://github.com/skydoves/sandwich/assets/84292117/e1f1cf35-d46b-4d29-8d40-a658bcfd1d45)

>  FATAL EXCEPTION: main
>                  Process: ..., PID: ...
>                  kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'error' at path: $
>                  Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
>                  JSON input: {"error":"Backend: user ..."}

**Comment by skydoves** [comment]
Hey @KovshefulCoder, sorry for the late response. As you said, the error body model must match your backend error body JSON model and its expected result.

**Comment by KovshefulCoder** [comment]
Yes, it should certainly match the JSON model to be converted into a @Serializable data class. However, I thibk that since we are discussing within the context of a library that allows working with the results of any request through a simple API, this case should also be converted into ApiResponse to enable processing it with the Sandwich API.

**Comment by KovshefulCoder** [comment]
@skydoves sorry for ping. What do you think?

**Comment by KovshefulCoder** [comment]
So, wrote down [extension](https://gist.github.com/KovshefulCoder/e546ed1f0979af56ac51e8a02eafc5f2) for this

**Comment by skydoves** [comment]
Looks very good to me, @KovshefulCoder. Thanks for sharing your experience with this community. Flexibility is one of the biggest strengths and features of this library, so it's good to see you make your custom extensions and resolve issues in dedicated ways.
