### ISSUE TITLE
Any Roadmap to Support Kotlin Multiplatform?

### ISSUE THREAD

**Issue by gusdoe** [skydoves/sandwich#270]
**Is your feature request related to a problem?**

No

**Describe the solution you'd like:**

Sample apps using KMM or KMP application with Hilt and ktor.

**Describe alternatives you've considered:**

Nil

**Comment by skydoves** [comment]
Hey @gusdoe, sandwich already supports KMP for `sandwich`, `sandwich-ktor`, `sandwich-ktorfit`, pakcages.

**Comment by gusdoe** [comment]
Thank you for your prompt answer!
