### ISSUE TITLE
Can I use Sandwich with Mongodb Realm API 

### ISSUE THREAD

**Issue by gusdoe** [skydoves/sandwich#273]
**Is your feature request related to a problem?**

I can't find any references and examples on how to use Sandwich with Mongodb Realm API access.

**Describe the solution you'd like:**

Documentation about if Sandwich is only available for HTTP and REST API. If applicable please provide instruction on how to use sandwich to connect Realm API  with samples.

**Describe alternatives you've considered:**

Manual exception control or backend server with Ktor(which I want to avoid)

**Comment by skydoves** [comment]
Hey @gusdoe, would you provide any samples on this? Also, you can create the `ApiResponse` instance from any kind of object or result.
