### ISSUE TITLE
Couldn't resolve ApiResponseCallAdapter class

### ISSUE THREAD

**Issue by yoonah5959** [skydoves/sandwich#282]
사용 버전: implementation("com.github.skydoves:sandwich:2.0.6")

문제 현상:
retrofit의 addConverterFactory(ApiResponseCallAdapterFactory.create()) 코드를 추가하려고 했으나 
ApiResponseCallAdapterFactory를 인식하지 못함 

addConverterFactory 없이 코드를 실행시키면 아래 에러가 남 
 java.lang.IllegalArgumentException: Unable to create converter for com.skydoves.sandwich.ApiResponse 

dependency 추가된 파일을 보면 ApiResponseCallAdapterFactory 모듈인 refrofit이 존재하지 않음 
<img width="456" alt="image" src="https://github.com/skydoves/sandwich/assets/28209510/a87103cf-273b-4bbe-8063-d47d4a5ff095">

라이브러리 사용을 잘못 한 것인지 아니면 이슈가 있는지 확인 부탁드립니다.

**Comment by skydoves** [comment]
안녕하세요 @yoonah5959, Retrofit의 경우는 아래 문서를 참조하시면 좋을 것 같습니다.

https://skydoves.github.io/sandwich/retrofit/

혹은 아래 의존성을 추가해주시길 바랍니다.

```kotlin
dependencies {
    implementation("com.github.skydoves:sandwich-retrofit:$version")
}
```
