### ISSUE TITLE
Global ApiResponseFailureMapper not returning desired results

### ISSUE THREAD

**Issue by robertszuba** [skydoves/sandwich#292]
First of all, thank you for creating this awesome library :) 

**Please complete the following information:**
- Library Version 2.0.5
 
**Describe the Bug:**
The library allows us to create custom error mappers and assign them globally, but because of the library internals the mapping result is not really returned to the app. Example below

Some dummy classes for failures:
```kotlin
class SandwichException(throwable: Throwable) : ApiResponse.Failure.Exception(throwable)
class SandwichError(payload: Any?) : ApiResponse.Failure.Error(payload)
```
and a dummy global mapper:
```kotlin
class ApiFailureMapper : ApiResponseFailureMapper {

    override fun map(apiResponse: ApiResponse.Failure<*>): ApiResponse.Failure<*> {
        return when (apiResponse) {
            is ApiResponse.Failure.Exception -> SandwichException(apiResponse.throwable)

            is ApiResponse.Failure.Error -> SandwichError(apiResponse.payload)
        }
    }
}

SandwichInitializer.sandwichFailureMappers.add(ApiFailureMapper())
```

Now when we face an exception, like IOExceptions, we can expect an instance of SandwitchException with IOException throwable, right? But instead we receive the original ApiResponse.Failure.Exception.

I did some investigation and I belive the error is caused by
https://github.com/skydoves/sandwich/blob/9a5ed854c1a84c66fad4cff020ead782628fdf99/sandwich/src/commonMain/kotlin/com/skydoves/sandwich/ApiResponse.kt#L110-L111
because `apply` will trigger lambda (operators and mappers) as expected, but the result is not assigned anywhere and the original Failure.Exception is returned.

**Expected Behavior:**

When using global operators and mappers the app should properly return the modified Failure.Exception instances

**Comment by skydoves** [comment]
Hey @robertszuba, thank you so much for reporting the valuable issue! It was fixed in the recent release (2.0.7), and I hope it works as you expected. Thank you!
