### ISSUE TITLE
multiplatform project

### ISSUE THREAD

**Issue by paparatsi40** [skydoves/sandwich#350]
build.gradle.kts (app) plugins block:

plugins {
    alias(libs.plugins.android_library)
    alias(libs.plugins.kotlin_multiplatform)
    alias(libs.plugins.compose_compiler)
}

Error: 

 Configure project :
e: file:///C:/Users/calfaro/AndroidStudioProjects/EchoMe2/build.gradle.kts:2:24: Unresolved reference: android_library
e: file:///C:/Users/calfaro/AndroidStudioProjects/EchoMe2/build.gradle.kts:3:24: Unresolved reference: kotlin_multiplatform
e: file:///C:/Users/calfaro/AndroidStudioProjects/EchoMe2/build.gradle.kts:4:24: Unresolved reference: compose_compiler

**Comment by skydoves** [comment]
It seems this error is not related to this library.
