### ISSUE TITLE
Ktor 3 + Ktorfit support

### ISSUE THREAD

**Issue by smelfungus** [skydoves/sandwich#386]
Hi! Thanks for the amazing library. I noticed that Ktor 3.0 has been released, so it might be a good time to consider updating Sandwich Ktorfit to ensure compatibility with the latest version. Ktorfit also recently introduced support for a separate set of artifacts, as mentioned here: https://github.com/Foso/Ktorfit/issues/681.

Thanks again for all your hard work!

**Comment by skydoves** [comment]
Hey @smelfungus, 2.0.10 support Ktor3 and Ktorfir-Ktor3 packages. Thank you so much for raising this issue!
