### ISSUE TITLE
Unresolved reference when adding dependency to a Kotlin module

### ISSUE THREAD

**Issue by FredNM** [skydoves/Sandwich#4]
Hi @skydoves, and thanks for this nice library

When adding this dependency to the `build.gradle` file of an Android module, it works fine.
But doing the same in the `build.gradle` of a pure Kotlin module, I'm not able to see the library (Unresolved reference). The IDE suggests "Add library 'Gradle: com.github.skydoves:sandwich:1.0.4@aar' to classpath"; and even doing that doesn't solve the problem.
This is my `build.gradle` file:
```gradle
apply plugin: 'kotlin'

dependencies {
    // some other dependencies
    implementation "com.github.skydoves:sandwich:1.0.4"
}
```
Could you explain how to handle this issue?
Thanks

**Comment by skydoves** [comment]
Hi, @FredNM.
I just tested and worked fine: New Project -> (After creating a new project) -> New Module -> Java or Kotlin Library -> (And I added the sandwich dependency)
Or Isn't that an Android project? (IntelliJ IDE, pure Kotlin project?)

**Comment by skydoves** [comment]
Hi, @FredNM!
This library will works when you use the below plugins together.
```gradle
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
``` 
This library uses some Android-based classes internally like `LiveData`, `Runnable`, `Handler`, etc.
Could you explain details about why this library should be used in a pure Kotlin project?
Thanks!

**Comment by FredNM** [comment]
Ok I understand. Thanks for answering.
Actually I have a multi-module app, and my remote module where I do the Retrofit requests is a pure Kotlin module. I will move it to an Android module. Thanks.
