### ISSUE TITLE
Issue with the ApiResponse.Failure<*>

### ISSUE THREAD

**Issue by CarlosEsco** [skydoves/Sandwich#41]
I have the following sample code and have my internet turned off. So an unresolved host is thrown

```
  val loginResponse = authService.login(loginRequest)

            loginResponse.onFailure {
                Timber.d("This Failed")
            }
            Timber.d("loginResponse is Failure ${loginResponse is ApiResponse.Failure<*>}}")
            Timber.d("loginResponse is Exception ${loginResponse is ApiResponse.Failure.Exception<*>}}")
```

Based off the comments and the types in onFailure,  both these timber log statements should be true and This Failed should print.  Since the comments for onFailure say "A function that would be executed for handling error responses if the request failed or get an exception."

**Comment by skydoves** [comment]
Hey @CarlosEsco,
Thanks for reporting this issue. The issue has been resolved in the new release `1.2.2`.
Btw, I looked around usages of this library on your open source project Neko, I feel it's such great. 😄 
Thanks for using this library and if you face any issues or would like to give feedback, feel free to reach out to me.
