### ISSUE TITLE
How to effectively combine sequential and parallel API calls, especially when one API depends on another?

### ISSUE THREAD

**Issue by e4basil** [skydoves/sandwich#414]
val api1 = remoteDataSource.doApi1()

        api1
            .suspendOnSuccess {
                db.api1DAO().insert(data.asEntity())
                emit(data)
            }
            .suspendThen { response ->
                remoteDataSource.doapi2()
            }
            .suspendOnSuccess {
                db.api2DAO().insertapi2(data.asEntity())
                data?.map { item ->
                    remoteDataSource.doapi3(item)
                }
            }
            // next step save both data to db
            // call other api
            // at last return status of completion true/ false
            .onError { onError(message()) }
            // handles the case when the API request gets an exception response.
            // e.g., network connection error.
            .onException { onError(message) }

**Comment by skydoves** [comment]
Hey @e4basil, sorry for the late response. it would be good to check out the comments here: #83

**Comment by skydoves** [comment]
This example might be helpful to implement that you wanted:

```kotlin
    loginAndRegister(orderData.phoneNumber).apply { emit(this) }
      .suspendMapSuccess {
        val jwt = "jwt ${data.auth.token}"
        Client.saveAuth(data)
        cancelOrder(
          orderData.orderId,
          OrderCancelRequestBody("store", "re-checkout")
        ).apply { emit(this) }.getOrThrow()
      }
      .suspendMapSuccess { addMultiCartItem(jwt, orderData.cartItems).apply { emit(this) }.getOrThrow() }
      .suspendMapSuccess { checkOut(orderData.checkoutBody!!).apply { emit(this) }.getOrThrow() }
      .suspendOnSuccess { emit(this) }
```
