### ISSUE TITLE
crash on 401 unauthorized status

### ISSUE THREAD

**Issue by iceberg1369** [skydoves/Sandwich#5]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**
when I send A user pass to my api which unauthorized and throws 401 status code. the apiresponse call adapter factory crashed.

    --------- beginning of crash
2020-09-12 14:16:55.564 7771-7771/com.skydoves.pokedex E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.skydoves.pokedex, PID: 7771
    retrofit2.HttpException: HTTP 401 Response.error()
        at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
        at com.skydoves.sandwich.coroutines.ApiResponseCallDelegate$enqueueImpl$1.onResponse(ApiResponseCallDelegate.kt:33)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

  onError expected to be fired

**Comment by skydoves** [comment]
@iceberg1369 
Hi, could you let me know about your details of the test codes?

**Comment by iceberg1369** [comment]
@skydoves 

`  @Provides
  @Singleton
  fun provideRetrofit(okHttpClient: OkHttpClient): Retrofit {
    return Retrofit.Builder()
      .client(okHttpClient)
      //.baseUrl("https://pokeapi.co/api/v2/")
            .baseUrl("http://37.152.179.135:8082/")
      .addConverterFactory(MoshiConverterFactory.create())
      .addCallAdapterFactory(CoroutinesResponseCallAdapterFactory())
      .build()
  }`

**Comment by iceberg1369** [comment]
@skydoves  is there anyway to handle errors in sandwitch

**Comment by nevermore1000** [comment]
i face the same issue，crash on ApiResponseCallDelegate.kt:33

**Comment by bogdanmunteanu** [comment]
I am facing the same issue : 401 returned instead of onError fired. Commenting to keep tabs on the issue

**Comment by skydoves** [comment]
I will check this issue and release the next version as soon as possible. Thanks!

**Comment by masterxing** [comment]
Hope to have a good solution

**Comment by bogdanmunteanu** [comment]
> Same thing happening for 500 errors , basically for what isn't in that success codes array in the initializer

**Comment by skydoves** [comment]
Please test using a new version `1.0.5-alpha01`!

**Comment by skydoves** [comment]
Hi, @iceberg1369 @masterxing @bogdanmunteanu @nevermore1000

Yesterday, released a new version [1.0.5](https://github.com/skydoves/Sandwich/releases/tag/1.0.5) ! 🎉 
Please try to test using the new version.

Thanks for reporting this issue! 👍

**Comment by bogdanmunteanu** [comment]
@skydoves , all working great for 401 and all 504 status codes (on error is triggered) . Will test more and come later with more feedback but all seems good for know. Thanks for the fast release 👍

**Comment by iceberg1369** [comment]
@skydoves 401 error handled by onError
