### ISSUE TITLE
Do not working when requesting api using coroutine.

### ISSUE THREAD

**Issue by shin-dongkyu** [skydoves/Sandwich#6]
- Library Version v1.0.5
- Affected Device(s) Samsung Galaxy s10 with Android 10

```
var testLiveData: LiveData<String>? = null
init {
    testRequest()
}

fun testRequest() {
    Timber.w("testRequest")
    testLiveData = launchOnViewModelScope {
        this.loginRepository.test(
            onSuccess = {
                Timber.w("onSuccess")
            },
            onError = {
                Timber.w("onError : $it")
            }
        ).asLiveData()
    }
}

button.setOnClickListener {
    viewModel.testRequest()
}

```

init{} is working...
but button click is not working

what is problem??

**Comment by skydoves** [comment]
Hi, @shin-dongkyu.

It seems you observing a null LiveData before assigning a `testLiveData` property.

> LiveData is an observable data holder class. Unlike a regular observable, LiveData is lifecycle-aware, meaning it respects the lifecycle of other app components, such as activities, fragments, or services. This awareness ensures LiveData only updates app component observers that are in an active lifecycle state.

LiveData is an observable data holder class that means it has a value property in the inner class.
So you can observe that class lazily after initializing it.

I can guess you referenced one of my repositories from the usage of `launchOnViewModelScope`.
The propose of the `launchOnViewModelScope` is that lanch 'something' in the viewModel scope, and emit it as a LiveData.
So If you want to observe pre-initialized LiveData using `Flow` (I don't know actually you used the `flow` in the repository.),
the codes must be like below.

```kotlin
val posterListLiveData = MutableLiveData<List<Poster>>()

fun getPost() {
  viewModelScope.launch {
      mainRepository.loadDisneyPosters(
          onSuccess = { _isLoading.postValue(false) },
          onError = { _toastLiveData.postValue(it) }
      ).collect {
        posterListLiveData.postValue(it)
      }
    }
}
```
