### ISSUE TITLE
Custom Error Handling

### ISSUE THREAD

**Issue by TrueKage** [skydoves/Sandwich#8]
Is there any way we can deserialize the json  in errorBody ?

**Comment by skydoves** [comment]
Hi,
You can resolve it using the [ApiErrorModeMapper](https://github.com/skydoves/sandwich#apierrormodelmapper).
The map function will receive the raw `ApiResponse.Failure.Error<*>` model and you can customize it to your own error response. And you can handle the customized model via the `map` extension.

**Comment by TrueKage** [comment]
Thanks 👍
