### ISSUE TITLE
[ASK] How can I handle 200 but error case?

### ISSUE THREAD

**Issue by chanjungkim** [skydoves/sandwich#85]
Some part of my app use Google Spreadsheet.

And I implemented REST API there with Apps Script.

I think this is rare case but, google server gives me 200 with html code when it has server error.

So, what I am trying is getting the response with ApiResponse<String>. And then try to convert the response to SpreadSheetResponseBody which is a data class when it's successful.

This is my concept.
```
    suspend fun updateDashboard(
        ssId: String,
        method: String,
        device: String,
        isTest: Boolean,
        request: KioskDashboardReqBody
    ): ApiResponse<SpreadSheetResponseBody>{
        val result = service.updateDashboard(ssId, method, device, isTest, request).onSuccess {
            try {
                val data = Gson().fromJson(this.data, SpreadSheetResponseBody::class.java)
                return ApiResponse.Success<SpreadSheetResponseBody>(data)
            }catch(e: Exception){
                return ApiResponse.Failure<SpreadSheetResponseBody>(e)
            }
        }
        return ApiResponse.Failure<SpreadSheetResponseBody>("Server Error")
    }
```
This code is invalid.
Since google gives me 200. I'd like to create ApiResponse instead in the Repository.

Is this possible to handling like this?

**Comment by skydoves** [comment]
Hey @chanjungkim, For sure you can like the example below:

```kotlin
val data = Gson().fromJson(this.data, SpreadSheetResponseBody::class.java)
val response = Response.success(data)
return ApiResponse.of { response }
```

**Comment by skydoves** [comment]
Hey @chanjungkim, For sure you can achieve it like the example below:

```kotlin
val data = Gson().fromJson(this.data, SpreadSheetResponseBody::class.java)
val response = Response.success(data)
return ApiResponse.of { response }
```

**Comment by chanjungkim** [comment]
Thanks you.

For the error case, I did like this. 

```
    suspend fun updateDashboard(
        ssId: String,
        method: String,
        device: String,
        isTest: Boolean,
        request: KioskDashboardReqBody
    ): ApiResponse<SpreadSheetResponseBody>{

        var result: Response<SpreadSheetResponseBody>? = null
        service.updateDashboard(ssId, method, device, isTest, request).onSuccess {
            result = try {
                val data = Gson().fromJson(this.data, SpreadSheetResponseBody::class.java)
                Response.success(data)
            }catch(e: Exception){
                Response.error(500, this.data.toResponseBody(null))
            }
        }

        return ApiResponse.of { result!! }
    }
```

Does it have any problem?

**Comment by skydoves** [comment]
If the JSON format fits well, it's the correct way that you have given to me.  For the content type, you can specify its plain text type rather than HTML type by giving `contentType = "text/plain".toMediaType()` to the parameter. You can log if the JSON format is correct by throwing an exception deliberately inside the try block. You can also check out the JSON formats for error responses [here](https://github.com/skydoves/sandwich/blob/main/sandwich-serialization/src/test/kotlin/com/skydoves/sandwich/serialization/SerializationExtensionsTest.kt#L34).
