### ISSUE TITLE
How to get custom error from my server?

### ISSUE THREAD

**Issue by longdcnb1998** [skydoves/sandwich#87]
When i call api to my server and handle error, i want to get my custom error message like this  
}
  "statusCode": 400,
  "message": "Registered phone number"
}

But when i use sandwich lib, error message convert to  [ApiResponse.Failure.Error-BadRequest](errorResponse=Response{protocol=http/1.1, code=400, message=Bad Request
I just want to get my message error "Registered phone number"

**Comment by skydoves** [comment]
Hey @longdcnb1998, sorry for the late response. You can check out #8.
