### ISSUE TITLE
[Help] Is it the best approach to validate responses?

### ISSUE THREAD

**Issue by ymaniz09** [skydoves/sandwich#88]
First, thanks for the fantastic lib!

I would like to double-check that I'm not over-complicating things 😅 
A pretty typical use case on my project is validating some fields in the successful response that might indicate abnormal behavior (some of them the app might know to handle)

Inside our repositories, we usually check some properties, and if everything is correct, we then map the network model to the UI model, otherwise will return an error result class wrapping it:

```
suspend fun doSomething(): MyResultWrapper<MyUIModel> {
        // We could get some error here and it will be handled by the VM
        val location = settingsStore.getLocation().dataOrNull() ?: return ApiResponse.Failure.Exception(
            IllegalArgumentException("Location should not be null")
        )

        return service.doSomething(request = location.id).let { response ->
            when {
                response is ApiResponse.Success && isInvalid(response.data) ->
                    ApiResponse.error(IllegalArgumentException("Some meaningful message"))
                else -> response
            }
        }.mapSuccess {
            toDomainModel()
        }
    }
```

Is that the correct way to handle that or am I missing something?

Thanks!!

**Comment by skydoves** [comment]
Hey @ymaniz09, this is very interesting that you should do a validation check on the client side. I recommend implementing a widely used extension for checking the validation and mapping if the condition does not meet the guarantee. For example, you can implement the extension like the below, and you can also use it commonly:

```kotlin
private fun <T> ApiResponse<T>.mapFailureIfInvalid(
  validation: (T) -> Boolean,
  errorResponse: () -> ApiResponse.Failure<T>
): ApiResponse<T> {
  if (this is ApiResponse.Success<T> && !validation.invoke(data)) {
    return errorResponse.invoke()
  }
  return this
}
```

Then, you can use it like the example below:

```kotlin
  suspend fun fetchPosters(): ApiResponse<List<Poster>> {
    return disneyService.fetchDisneyPosters().mapFailureIfInvalid(
      validation = { data -> isValid(data) },
      errorResponse = {
        ApiResponse.error(IllegalArgumentException("Some meaningful message"))
      }
    )
  }
```

Btw, this is very interesting question. Let me know what you think of the solution above. Thanks!

**Comment by ymaniz09** [comment]
@skydoves Thank you so much for the quick answer!
Amazing solution; I really appreciate it. 

I'm giving it a try right away
