### ISSUE TITLE
EmptyBodyInterceptor doesn't work with GsonConverterFactory

### ISSUE THREAD

**Issue by katajona** [skydoves/sandwich#98]
**Please complete the following information:**
- Library Version v1.3.4
 
**Describe the Bug:**
When using`EmptyBodyInterceptor` to enable nullable bodies I get an exception 
```
OFException: End of input at line 1 column 1 path $
    at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1421)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
    at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:42)
...
```
Issue is caused by GsonConverterFactory because `""` is not a valid Json.
https://github.com/google/gson/issues/330

**Expected Behavior:**
No exception is thrown when using `EmptyBodyInterceptor` with `GsonConverterFactory`

**Comment by skydoves** [comment]
This issue is more highly related to Gson than this library. Would you use Moshi or Kotlin serialization instead of Gson? Actually, Gson is abandoned by the original contributors.

**Comment by skydoves** [comment]
Check out this: https://stackoverflow.com/questions/60856421/gson-treat-empty-string-as-null

**Comment by katajona** [comment]
I tried using that but it didn't help. Of course, switching the serializer would solve this but would have been nice to be able to stay with the one we have. Do you plan to support Gson or is it only Moshi/Kotlin serialization that you support?

**Comment by skydoves** [comment]
@katajona Unfortunately, there's nothing that I can do about this from my side because this issue came from Gson. You should write your own `TypeAdapter`, which converts an empty string to null or something.

**Comment by skydoves** [comment]
Or it's quite a tricky way - writing copy and past `EmptyBodyInterceptor` in your local project and change, and tweak the empty body as the below:

```kotlin
val emptyBody = "emptyBody".toResponseBody("text/plain".toMediaType())
```

And you should treat the string response, which equals "emptyBody" as an empty body.

**Comment by skydoves** [comment]
I hope my answer was helpful to you :) I will close this issue now because there's nothing much that I can do from my side.
